- name: Install iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Configure iptables rules
  ansible.builtin.template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
    backup: true
  notify: restore iptables

- name: Ensure iptables-persistent is enabled
  ansible.builtin.systemd:
    name: netfilter-persistent
    enabled: true
    state: started
