- name: Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Configure iptables rules
  template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
    mode: "0644"
    backup: true
  notify: restore iptables

- name: Ensure iptables-persistent is enabled
  systemd:
    name: netfilter-persistent
    enabled: true
    state: started
