---
ptp:
  # Port configuration
  master_port: mgbe0
  slave_ports:
    - eqos0
    - eth0
  
  # ptp4l configuration values
  clock_class: 248  # ptp4l default value
  priority1: 128    # ptp4l default value
  priority2: 128    # ptp4l default value

# Service files directory
ptp_service_dir: /opt/drs/service/ptp