---
- name: Build ros2_bridge packages
  ansible.builtin.shell:
    cd {{ drs_src_dir }}
    source /opt/drs/config/drs.env
    source /opt/ros/humble/setup.bash
    colcon build --merge-install --install-base {{ drs_install_dir }} --cmake-args -DCMAKE_BUILD_TYPE={{ drs_build_type }} --packages-select ros2_bridge
  args:
    executable: /bin/bash

- name: Create ros2_bridge service directory
  file:
    path: /opt/drs/service/ros2_bridge
    state: directory
    owner: "{{ drs_user }}"
    group: "{{ drs_group }}"
    mode: '0755'
  become: yes

- name: Copy ros2_bridge launch script
  ansible.builtin.template:
    src: launch.sh.j2
    dest: /opt/drs/service/ros2_bridge/launch.sh
    owner: "{{ drs_user }}"
    group: "{{ drs_group }}"
    mode: '0755'
  become: yes

- name: Deploy drs-ros2-bridge systemd service file
  template:
    src: drs-ros2-bridge.service.j2
    dest: /etc/systemd/system/drs-ros2-bridge.service
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: yes

- name: Enable and start drs-ros2-bridge service
  systemd:
    name: drs-ros2-bridge
    enabled: yes
    state: started
  become: yes