---
- name: Install v4l-utils
  apt:
    name: v4l-utils
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Add user to i2c group
  user:
    name: "{{ drs_user }}"
    groups: i2c
    append: true
  become: true
