repos:
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v24.2.0
    hooks:
      - id: ansible-lint
        additional_dependencies: 
          - ansible-core>=2.14.0
        language_version: python3.12
