- name: Install ptpd
  ansible.builtin.apt:
    name:
      - ptpd
    update_cache: true
  become: true

- name: Copy service template file
  ansible.builtin.copy:
    src: ptpd_slave@.service
    dest: /etc/systemd/system/
  become: true

- name: Install ptpd client service file
  ansible.builtin.systemd:
    name: ptpd_slave@{{ item }}.service
    daemon_reload: true
    enabled: true
    masked: false
  become: true
  with_items: "{{ ptpd_client_interfaces }}"
