- name: Install ptpd
  ansible.builtin.apt:
    name:
      - ptpd
    update_cache: true
  become: true

- name: Copy service template file
  ansible.builtin.template:
    src: ptpd_slave@.service.jinja2
    dest: /etc/systemd/system/ptpd_slave@.service
  become: true

- name: Install ptpd client service file
  ansible.builtin.systemd:
    name: ptpd_slave@{{ item }}.service
    daemon_reload: true
    enabled: true
    masked: false
  become: true
  with_items: "{{ ptpd_client_interfaces }}"

- name: Save service name for later use
  set_fact:
    enabled_ptpd_services: "{{ (enabled_ptpd_services | default([])) + ['ptpd_slave@' + item + '.service'] }}"
  with_items: "{{ ptpd_client_interfaces }}"
