# ECU0 specific configuration

drs_ecu_id: 0
module_id: eNdWhZgc

has_vehicle_can: true
has_fisheye: false
has_dashboard_service: true # JPT#10 needs this for drs_ros2_bridge_service

# Module manager configuration
module_manager_config: module-manager-ecu0.yaml

# Use ECU0 specific netplan configuration
netplan_files:
  - 99-drs-ecu0.yaml

# PTP Configuration
ptp:
  time_sync_type: GNSS # GNSS or NTP
  ntp_server: ntp.nict.jp
  master_port: mgbe0
  slave_ports:
    - enP1p1s0
    - eqos0
  clock_class: 187
  priority1: 128
  priority2: 128

# NTP Server Configuration for ECU0
# Override ntp_server_enabled here to enable NTP server on this host
# This distributes PTP-synchronized system time as NTP server
# WARNING: Cannot be enabled when ptp.time_sync_type is 'NTP'
# ntp_server_enabled: true

# NAS Configuration
nas_address: 192.168.10.100

# ECU0 specific network interfaces for CycloneDDS
cyclonedds:
  network_interface: [lo, enP1p1s0]
  minimum_socket_receive_buffer_size: 20MB
  ipfrag_time: 3
  ipfrag_high_thresh: 134217728
  rmem_max: 2147483647
  rmem_default: 8388608
