---
# ECU0 specific configuration

drs_ecu_id: 0

# Use ECU0 specific netplan configuration
netplan_files:
  - 99-drs-ecu0.yaml

# ECU0 specific network interfaces for CycloneDDS
cyclonedds:
  network_interface: ['lo', 'enP1p1s0']
  minimum_socket_receive_buffer_size: 20971520  # 20MB
  ipfrag_time: 3
  ipfrag_high_thresh: 134217728
  rmem_max: 2147483647
  rmem_default: 8388608