# ECU1 specific configuration

drs_ecu_id: 1

has_vehicle_can: false
has_dashboard_service: false

# Module manager configuration
module_manager_config: module-manager-ecu1.yaml

# Use ECU1 specific netplan configuration
netplan_files:
  - 99-drs-ecu1.yaml

# PTP Configuration
ptp:
  time_sync_type: GNSS # Always use GNSS (Standard PTP) for ECU1 as it is a slave
  ntp_server: ntp.nict.jp # Placeholder, not used in GNSS mode
  master_port: enP1p1s0
  slave_ports:
    - eqos0
  clock_class: 248
  priority1: 128
  priority2: 128

# NAS Configuration
nas_address: 192.168.10.101

# ECU1 specific network interfaces for CycloneDDS
cyclonedds:
  network_interface: [lo, enP1p1s0]
  minimum_socket_receive_buffer_size: 20MB
  ipfrag_time: 3
  ipfrag_high_thresh: 134217728
  rmem_max: 2147483647
  rmem_default: 8388608
