---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start mount unit
  ansible.builtin.systemd:
    name: mnt-external-data.mount
    enabled: yes
    state: started