- name: Create journald.conf.d directory
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    mode: "0755"

- name: Configure journald
  ansible.builtin.template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf.d/drs.conf
    mode: "0644"
  notify: restart systemd-journald
