---
# Local inventory file for running ansible on the same host

all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: "{{ lookup('env', 'USER') }}"
    ecu0:
      ansible_host: 127.0.0.1
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: "{{ lookup('env', 'USER') }}"
    ecu1:
      ansible_host: 127.0.0.1
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: "{{ lookup('env', 'USER') }}"
    raspi:
      ansible_host: 127.0.0.1
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: "{{ lookup('env', 'USER') }}"