---
- name: Enable vehicle section in drs_ecu0.launch.xml
  ansible.builtin.replace:
    path: "{{ drs_install_dir }}/share/drs_launch/launch/drs_ecu0.launch.xml"
    regexp: |
      (?m)^  <!-- vehicle -->\s*$
      ^  <!--\s*$
      ^  <group>\s*$
      ^    <push-ros-namespace namespace="vehicle"/>\s*$
      ^    <include file="\$\(find-pkg-share drs_launch\)/launch/component/vehicle\.launch\.xml">\s*$
      ^      <arg name="launch_driver" value="\$\(var live_sensor\)"/>\s*$
      ^    </include>\s*$
      ^  </group>\s*$
      ^  -->\s*$
    replace: |
      <!-- vehicle -->
      <group>
        <push-ros-namespace namespace="vehicle"/>
        <include file="$(find-pkg-share drs_launch)/launch/component/vehicle.launch.xml">
          <arg name="launch_driver" value="$(var live_sensor)"/>
        </include>
      </group>
  become: true
  when:
    - drs_ecu_id == 0 or drs_ecu_id == '0'
    - vehicle_can_enabled | bool
  notify: restart drs-sensor

- name: Disable vehicle section in drs_ecu0.launch.xml
  ansible.builtin.replace:
    path: "{{ drs_install_dir }}/share/drs_launch/launch/drs_ecu0.launch.xml"
    regexp: |
      (?m)^  <!-- vehicle -->\s*$
      ^  <group>\s*$
      ^    <push-ros-namespace namespace="vehicle"/>\s*$
      ^    <include file="\$\(find-pkg-share drs_launch\)/launch/component/vehicle\.launch\.xml">\s*$
      ^      <arg name="launch_driver" value="\$\(var live_sensor\)"/>\s*$
      ^    </include>\s*$
      ^  </group>\s*$
    replace: |
      <!-- vehicle -->
      <!--   
      <group>
        <push-ros-namespace namespace="vehicle"/>
        <include file="$(find-pkg-share drs_launch)/launch/component/vehicle.launch.xml">
          <arg name="launch_driver" value="$(var live_sensor)"/>
        </include>
      </group>
      -->
  become: true
  when:
    - drs_ecu_id == 0 or drs_ecu_id == '0'
    - not (vehicle_can_enabled | bool)
  notify: restart drs-sensor

- name: Enable /vehicle/from_can_bus topic in record_topics_ecu0.yaml
  ansible.builtin.replace:
    path: "/opt/drs/config/record_topics_ecu0.yaml"
    regexp: '^#\s+- name: /vehicle/from_can_bus'
    replace: '  - name: /vehicle/from_can_bus'
  become: true
  when:
    - drs_ecu_id == 0 or drs_ecu_id == '0'
    - vehicle_can_enabled | bool
  notify: restart drs-recorder

- name: Disable /vehicle/from_can_bus topic in record_topics_ecu0.yaml
  ansible.builtin.replace:
    path: "/opt/drs/config/record_topics_ecu0.yaml"
    regexp: '^\s+- name: /vehicle/from_can_bus'
    replace: '#  - name: /vehicle/from_can_bus'
  become: true
  when:
    - drs_ecu_id == 0 or drs_ecu_id == '0'
    - not (vehicle_can_enabled | bool)
  notify: restart drs-recorder

