- name: Copy service body script
  ansible.builtin.template:
    src: check_ptpd.sh.jinja2
    dest: /opt/drs/check_ptpd.sh
  become: true

- name: Copy service template files
  block:
    - name: Copy callee service template
      ansible.builtin.template:
        src: check_ptpd.service.jinja2
        dest: /etc/systemd/system/check_ptpd.service
    - name: Copy timer service template
      ansible.builtin.template:
        src: check_ptpd.timer.jinja2
        dest: /etc/systemd/system/check_ptpd.timer
  become: true

- name: Install services
  block:
    - name: enable callee service
      ansible.builtin.systemd:
        name: check_ptpd.service
        daemon_reload: true
        enabled: true
    - name: enable timer service
      ansible.builtin.systemd:
        name: check_ptpd.timer
        daemon_reload: true
        enabled: true
  become: true

