#!/bin/bash

# Basic prompt with colors
export PS1="\[\e[31m\]drs-docker\[\e[m\] \[\e[33m\]\w\[\e[m\] > "
export TERM=xterm-256color

# Enable color support for ls and add useful aliases
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add color support for grep
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# History settings
export HISTSIZE=1000
export HISTFILESIZE=2000
export HISTCONTROL=ignoreboth

# Append to the history file, don't overwrite it
shopt -s histappend

# Check window size after each command
shopt -s checkwinsize

# Source ROS 2 environment
if [ -f /opt/ros/$ROS_DISTRO/setup.bash ]; then
    source /opt/ros/$ROS_DISTRO/setup.bash
fi

# Source DRS environment
if [ -f /opt/drs/install/setup.bash ]; then
    source /opt/drs/install/setup.bash
fi
