---
- name: Install iptables
  apt:
    name: iptables
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Create iptables service directory
  file:
    path: /opt/drs/service/iptables
    state: directory
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Deploy iptables rules script
  template:
    src: add_iptables_rules.sh.j2
    dest: /opt/drs/service/iptables/add_iptables_rules.sh
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Deploy iptables systemd service
  template:
    src: iptables.service.j2
    dest: /etc/systemd/system/iptables.service
    mode: "0644"
    owner: root
    group: root
  notify: reload systemd
  become: true

- name: Enable iptables service
  systemd:
    name: iptables
    enabled: true
    daemon_reload: true
  become: true
