- name: Install netplan
  ansible.builtin.apt:
    name: netplan.io
    update_cache: true
  become: true

- name: Copy network config file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /etc/netplan
    mode: 0644
  with_items: "{{ netplan_files }}"
  become: true

- name: Netplan apply
  command: netplan apply
  become: true
