- name: Create DRS installation directory
  file:
    path: "{{ drs_install_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ drs_user }}"
    group: "{{ drs_group }}"
  become: true

# todo: Inspect failed tasks and fix them
# - name: Import dependencies using vcs from drs.repos
#   shell: |
#     cd {{ drs_src_dir }}
#     vcs import src < drs.repos
#   args:
#     executable: /bin/bash
#   become_user: {{ drs_user }}
#   environment:
#     HOME: /home/{{ drs_user }}

- name: Initialize rosdep system-wide
  shell: |
    rosdep init
  args:
    executable: /bin/bash
  become: true
  ignore_errors: true

- name: Update rosdep for user
  shell: |
    rosdep update
  args:
    executable: /bin/bash
  become_user: "{{ drs_user }}"
  environment:
    HOME: "/home/{{ drs_user }}"

- name: Install ROS dependencies with rosdep
  shell: |
    cd {{ drs_src_dir }}
    source /opt/ros/humble/setup.bash
    rosdep install -y -r --from-paths src --ignore-src
  args:
    executable: /bin/bash
  become_user: "{{ drs_user }}"
  environment:
    HOME: "/home/{{ drs_user }}"

- name: Build DRS packages directly to installation directory
  shell: |
    cd {{ drs_src_dir }}
    source /opt/drs/config/drs.env
    source /opt/ros/humble/setup.bash
    colcon build --merge-install --install-base {{ drs_install_dir }} --cmake-args -DCMAKE_BUILD_TYPE={{ drs_build_type }} --packages-up-to {{ drs_packages | join(' ') }}
    chown -R "{{ drs_user }}:{{ drs_group }}" "{{ drs_install_dir }}"
  args:
    executable: /bin/bash
