---
- name: Install hostapd and related packages
  apt:
    name:
      - hostapd
      - wireless-tools
      - wpasupplicant
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Stop hostapd service temporarily
  systemd:
    name: hostapd
    state: stopped

- name: Configure hostapd
  template:
    src: hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
    mode: "0600"
    backup: true

- name: Configure hostapd daemon
  lineinfile:
    path: /etc/default/hostapd
    regexp: "^#?DAEMON_CONF="
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
    create: true

- name: Unmask hostapd service
  systemd:
    name: hostapd
    masked: false

- name: Enable hostapd
  systemd:
    name: hostapd
    enabled: true
