- name: Install hostapd and related packages
  ansible.builtin.apt:
    name:
      - hostapd
      - wireless-tools
      - wpasupplicant
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: Stop hostapd service temporarily
  ansible.builtin.systemd:
    name: hostapd
    state: stopped

- name: Configure hostapd
  ansible.builtin.template:
    src: hostapd.conf.j2
    dest: /etc/hostapd/hostapd.conf
    mode: "0600"
    backup: true

- name: Configure hostapd daemon
  ansible.builtin.lineinfile:
    path: /etc/default/hostapd
    # yamllint disable-line rule:quoted-strings
    regexp: "^#?DAEMON_CONF="
    line: DAEMON_CONF="/etc/hostapd/hostapd.conf"
    create: true
    mode: "0644"

- name: Unmask hostapd service
  ansible.builtin.systemd:
    name: hostapd
    masked: false

- name: Enable hostapd
  ansible.builtin.systemd:
    name: hostapd
    enabled: true
