---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: restart drs-recorder
  ansible.builtin.systemd:
    name: drs-recorder.service
    state: restarted
  become: true
