- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Restart drs-sensor
  ansible.builtin.systemd:
    name: drs-sensor.service
    state: restarted
  become: true
