---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: restart drs-sensor
  ansible.builtin.systemd:
    name: drs-sensor.service
    state: restarted
  become: true
