- name: Install dependencies for drs_transfer
  ansible.builtin.apt:
    name:
      - util-linux # For flock command
    state: present
    update_cache: true
  become: true

- name: Create drs_transfer directory
  ansible.builtin.file:
    path: "{{ drs_transfer_script_path | dirname }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create sync script from template
  ansible.builtin.template:
    src: drs_transfer.sh.j2
    dest: "{{ drs_transfer_script_path }}"
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create systemd service file
  ansible.builtin.template:
    src: drs-transfer.service.j2
    dest: /etc/systemd/system/drs-transfer.service
    owner: root
    group: root
    mode: "0644"
  register: systemd_service
  become: true

- name: Create systemd timer file
  ansible.builtin.template:
    src: drs-transfer.timer.j2
    dest: /etc/systemd/system/drs-transfer.timer
    owner: root
    group: root
    mode: "0644"
  register: systemd_timer
  become: true

- name: Reload systemd if service files changed
  ansible.builtin.systemd:
    daemon_reload: true
  when: systemd_service.changed or systemd_timer.changed
  become: true

- name: Enable and start drs-transfer timer
  ansible.builtin.systemd:
    name: drs-transfer.timer
    state: started
    enabled: true
  become: true
