- name: Create recorder service directory
  ansible.builtin.file:
    path: /opt/drs/service/drs_recorder
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Create data recording directory
  ansible.builtin.file:
    path: "{{ drs_recorder_data_dir }}"
    state: directory
    owner: "{{ drs_user }}"
    group: "{{ drs_group }}"
    mode: "0755"
  become: true

- name: Create recorder launch script
  ansible.builtin.template:
    src: launch.sh.jinja2
    dest: /opt/drs/service/drs_recorder/launch.sh
    owner: root
    group: root
    mode: "0755"
  become: true
  notify: restart drs-recorder

- name: Deploy recorder topics configuration
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: /opt/drs/config/{{ item }}
    owner: root
    group: root
    mode: "0644"
  become: true
  loop:
    - record_topics_ecu0.yaml
    - record_topics_ecu1.yaml
  notify: restart drs-recorder

- name: Copy mcap options
  ansible.builtin.copy:
    src: mcap_options.yaml
    dest: /opt/drs/config/mcap_options.yaml
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: restart drs-recorder

- name: Create systemd service file
  ansible.builtin.template:
    src: drs-recorder.service.jinja2
    dest: /etc/systemd/system/drs-recorder.service
    owner: root
    group: root
    mode: "0644"
  become: true
  notify:
    - reload systemd
    - restart drs-recorder

- name: Enable and start recorder launch service
  ansible.builtin.systemd:
    name: drs-recorder.service
    daemon_reload: true
    enabled: true
    state: started
  become: true
