- name: Setup DRS related stuff
  hosts: localhost
  vars:
    - drs_user_name: "{{ lookup('env', 'USER') }}"
    - record_root_directory: "{{ lookup('env', 'HOME') }}/nas"
    - drs_source_dir: "{{ playbook_dir | dirname }}" # `dirname` get the parent directory
    - autoware_env_dir: /opt/autoware/env
    - ros_distro: humble
    - network_config:
        ros:
          interface_address: 192.168.2.2
          interface_name: eqos0
        dhcp:
          interface_name: mgbe1
        lidar:
          interface_address: 192.168.1.100
          interface_name: eth0
    - ptp4l_client_interface: eqos0
    - ptp4l_host_interface: eth0
  vars_prompt:
    - name: drs_ecu_id
      prompt: |-
        Enter ECU ID to be setup
      private: false
      confirm: yes

  roles:
    - role: drs_env_setting
    - role: rosbag_record_service
    - role: drs_launch_service
    - role: rosbag_restart_cron
    - role: auto_storage_mount
    - role: can_network_setting
      when: drs_ecu_id == '0'
    - role: enable_auto_login
      when: drs_ecu_id == '0'
    - role: install_autoboot_interface
      when: drs_ecu_id == '0'
  environment:
    DEBIAN_FRONTEND: noninteractive
