- name: Setup DRS related stuff
  hosts: localhost
  vars:
    - drs_user_name: "{{ lookup('env', 'USER') }}"
    - record_root_directory: "{{ lookup('env', 'HOME') }}/nas"
    - local_storages:
        number_of_storages: 2
        prefix: "{{ lookup('env', 'HOME') }}/ssd"
    - drs_source_dir: "{{ playbook_dir | dirname }}" # `dirname` get the parent directory
    - autoware_env_dir: /opt/autoware/env
    - ros_distro: humble
    - network_config:
        ros:
          interface_address_base: 192.168.20
          interface_name: eth0
        nas:
          interface_address_base: 192.168.10
          interface_name: mgbe1
          mtu: 9000
        long_range_lidar:
          interface_address_base: 192.168.2
          interface_name: mgbe0
        mid_range_lidar:
          interface_address_base: 192.168.3
          interface_name: eqos0
        ins:
          interface_address_base: 192.168.4
          interface_name: eth1

    - ptp4l_client_interface: eqos0
    - ptp4l_host_interface: eth0
  vars_prompt:
    - name: drs_ecu_id
      prompt: |-
        Enter ECU ID to be setup [0/1]
      private: false
      confirm: yes
    - name: drs_system_uuid
      prompt: |-
        Enter SYSTEM UUID for this ECU
      private: false

  roles:
    - role: disable_systemd_timesyncd
    - role: cyclonedds
    - role: enlarge_txqueue
    - role: drs_env_setting
    - role: rosbag_record_service
    - role: drs_launch_service
    - role: rosbag_restart_cron
    - role: auto_storage_mount
    - role: set_local_multicast
    - role: cgroups
    - role: can_network_setting
      when: drs_ecu_id == '0'
    - role: enable_auto_login
      when: drs_ecu_id == '0'
    - role: install_autoboot_interface
      when: drs_ecu_id == '0'
    - role: ptpd_host
      vars:
        ptpd_host_interfaces:
          - mgbe0
          - eqos0
    - role: ptpd_host
      vars:
        ptpd_host_interfaces:
          - eth0
      when: drs_ecu_id == '1'
    - role: ptpd_client
      vars:
        ptpd_client_interfaces:
          - eth1
      when: drs_ecu_id == '1'
    - role: ptpd_client
      vars:
        ptpd_client_interfaces:
          - eth0
      when: drs_ecu_id == '0'
    - role: ssh_key_gen
      when: drs_ecu_id == '0'
    - role: visudo_for_no_password
    - role: netplan  # This role should be come at the very last of roles

  environment:
    DEBIAN_FRONTEND: noninteractive
