- name: Install cyclonedds dependencies
  ansible.builtin.package:
    name:
      - ros-humble-rmw-cyclonedds-cpp
    state: present
  become: true
  failed_when: false  # Allow failure if ROS2 is not installed

- name: Create cyclonedds directory
  ansible.builtin.file:
    path: /opt/drs/config/
    state: directory
    mode: 0755
  become: true

- name: Copy cyclonedds config
  ansible.builtin.template:
    src: cyclonedds.xml.jinja2
    dest: /opt/drs/config/cyclonedds.xml
    mode: 0755
  become: true

- name: Copy multicast setup service
  ansible.builtin.copy:
    src: cyclonedds-local.service
    dest: /etc/systemd/system/
    mode: 0755
  become: true
  when: '"lo" in cyclonedds.network_interface'

- name: Enable and start cyclonedds-local service
  ansible.builtin.systemd:
    name: cyclonedds-local.service
    enabled: true
    state: started
  become: true
  when: '"lo" in cyclonedds.network_interface'

- name: Add kernel parameter config
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    sysctl_file: /etc/sysctl.d/60-cyclonedds.conf
  with_dict:
    net.ipv4.ipfrag_time: "{{ cyclonedds.ipfrag_time }}"
    net.ipv4.ipfrag_high_thresh: "{{ cyclonedds.ipfrag_high_thresh }}"
    net.core.rmem_max: "{{ cyclonedds.rmem_max }}"
    net.core.rmem_default: "{{ cyclonedds.rmem_default }}"
  become: true

- name: Add settings to drs.env
  ansible.builtin.blockinfile:
    path: /opt/drs/config/drs.env
    state: present
    create: true
    mode: 0644
    marker: "# {mark} cyclonedds"
    block: |
      export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      export CYCLONEDDS_URI=file:///opt/drs/config/cyclonedds.xml
  become: true
