- name: Install nfs-common package to support NFS mount
  ansible.builtin.apt:
    name:
      - nfs-common
    update_cache: true
  become: true

- name: Create mount point
  ansible.builtin.file:
    path: "{{ record_root_directory }}"
    state: directory

- name: Configure auto mount NAS
  ansible.posix.mount:
    src: 192.168.10.100:/volume1/data
    path: "{{ record_root_directory }}"
    fstype: nfs
    opts: v4.1,user,rw,x-systemd.automount,x-systemd.requires=network-online.target
    state: present
    boot: true
  become: true

- name: Configure auto mount SSD
  ansible.posix.mount:
    src: "UUID={{ dummy_uuid }}" # TODO: parse mounted SSID, if possible
    path: "{{ local_storages.prefix + '{}'.format(item)}}"
    fstype: ext4
    opts: defaults
    state: present
    boot: true
  become: true
  with_items:
    - "{{ range(1, local_storages.number_of_storages + 1) | list }}"

- name: Force systemd to reload config
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
