name: pre-commit-ansible

on:
  pull_request:

jobs:
  pre-commit-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Ansible collections for lint
        run: |
          python3 -m pip install --user 'ansible-core>=2.18,<2.19'
          ansible-galaxy collection install -r ansible/requirements.yml -p ansible/collections
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
          ANSIBLE_COLLECTIONS_PATHS: ansible/collections:~/.ansible/collections:/usr/share/ansible/collections

      - name: Run pre-commit
        uses: autowarefoundation/autoware-github-actions/pre-commit@v1
        with:
          pre-commit-config: .pre-commit-config-ansible.yaml
        env:
          ANSIBLE_CONFIG: ansible/ansible.cfg
          ANSIBLE_COLLECTIONS_PATHS: ansible/collections:~/.ansible/collections:/usr/share/ansible/collections
