topics:
  - name: /sensing/camera/camera0/image_raw/compressed
    min_rate: 18.0
    max_rate: 21.0
  - name: /sensing/camera/camera1/image_raw/compressed
    min_rate: 18.0
    max_rate: 21.0
  - name: /sensing/camera/camera2/image_raw/compressed
    min_rate: 18.0
    max_rate: 21.0
  - name: /sensing/camera/camera3/image_raw/compressed
    min_rate: 18.0
    max_rate: 21.0
  - name: /sensing/camera/camera0/camera_info
    min_rate: 18.0
    max_rate: 21.0
  - name: /sensing/camera/camera1/camera_info
    min_rate: 18.0
    max_rate: 21.0
  - name: /sensing/camera/camera2/camera_info
    min_rate: 18.0
    max_rate: 21.0
  - name: /sensing/camera/camera3/camera_info
    min_rate: 18.0
    max_rate: 21.0
  - name: /sensing/lidar/front/seyond_packets
    min_rate: 9.0
    max_rate: 15.0
  - name: /sensing/lidar/right/seyond_packets
    min_rate: 9.0
    max_rate: 15.0
  - name: /tf_static # tf
    min_rate: 0.1
    max_rate: 10.0
  - name: /sensing/ins/oxts/imu
    min_rate: 45.0
    max_rate: 55.0
  - name: /sensing/ins/oxts/imu_bias
    min_rate: 4.0
    max_rate: 6.0
  - name: /sensing/ins/oxts/lever_arm
    min_rate: 4.0
    max_rate: 6.0
  - name: /sensing/ins/oxts/nav_sat_fix
    min_rate: 9.0
    max_rate: 12.0
  - name: /sensing/ins/oxts/nav_sat_ref
    min_rate: 9.0
    max_rate: 12.0
  - name: /sensing/ins/oxts/ncom
    min_rate: 95.0
    max_rate: 105.0
  - name: /sensing/ins/oxts/odometry
    min_rate: 45.0
    max_rate: 55.0
  - name: /sensing/ins/oxts/velocity
    min_rate: 45.0
    max_rate: 55.0
  - name: /vehicle/from_can_bus
    min_rate: 300.0
    max_rate: 1500.0
